### PR TITLE
frontend edits 6/30/2022

### PR DESCRIPTION
**Pull request by greenje262**
added phone number formatting, button disable on form submit, and changed name assignments to ease backend organization

### CODE REVIEW

**Comment by bfrey08** [comment]
I tweaked the formatting of the invite params to better mesh with the controller and changed the controller

**Comment by bfrey08** [comment]
button disable is awesome

**Comment by bfrey08** [comment]
phone number formatting does not appear to be working? maybe I'm missing something.

P.S. I see you making a more mobile friendly version over there

**Comment by greenje262** [comment]
phone number formatting should be working now

**Comment by bfrey08** [comment]
added validations so only properly formatted phone numbers can get saved to the DB

**Pull request merged**
